---
# tasks file for docker


- name: Ensure docker is installed
  yum:
    name: "docker"
    state: latest
    update_cache: yes

- name: Add the user 'ec2-user' and add it to 'docker'
  user:
    name: ec2-user
    create_home: yes 
    state: present 
    generate_ssh_key: false

- name : "Create Groups"
  group:
    name: "docker"
    state: "present" 

- ansible.builtin.user:
    name: ec2-user
    shell: /bin/bash
    groups: docker
    append: yes

- name: Enable Docker CE service at startup
  service:
    name: docker
    state: started
    enabled: yes

