---
# tasks file for common-setup-role
#
- name: Expose Dockerhost - replace line in file
  shell: sed -i "/.*ExecStart=.*/c\\ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock" /lib/systemd/system/docker.service

# - name: Reload docker deamon
#   shell: systemctl daemon-reload

# - name: Force systemd to reread configs
#   systemd: daemon_reload=yes

# - name: sudo service docker restart
#   shell: service docker restart

- name: restart docker service
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: verify accessibility to Master
  uri:
    url: "http://{{ private_ip }}:4243/version"
    method: GET
    timeout: 30
    return_content: yes
  register: out

- name: Print the msg
  debug:
    msg: "{{ out }}"

# - name: verify accessibility
#   shell: curl http://{{ private_ip }}:4243/version



# - name: verify accessibility - Localhost
#   shell: curl http://localhost:4243/version

- name: verify accessibility to Localhost
  uri:
    url: "http://localhost:4243/version"
    method: GET
    timeout: 30
    return_content: yes
  register: out

- name: Print the msg
  debug:
    msg: "{{ out }}"